
package sos.haruhi.ws.service;

import sos.haruhi.ws.pojo.User;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IUserService", targetNamespace = "http://sos.haruhi.ws/test/")
public interface IUserService {


    /**
     * 
     * @param user
     */
    @WebMethod
    @RequestWrapper(localName = "add", targetNamespace = "http://sos.haruhi.ws/test/", className = "ws.haruhi.sos.test.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://sos.haruhi.ws/test/", className = "ws.haruhi.sos.test.AddResponse")
    public void add(
            @WebParam(name = "user", targetNamespace = "")
                    User user);

    /**
     * 
     * @param username
     */
    @WebMethod
    @RequestWrapper(localName = "del", targetNamespace = "http://sos.haruhi.ws/test/", className = "ws.haruhi.sos.test.Del")
    @ResponseWrapper(localName = "delResponse", targetNamespace = "http://sos.haruhi.ws/test/", className = "ws.haruhi.sos.test.DelResponse")
    public void del(
            @WebParam(name = "username", targetNamespace = "")
                    String username);

    /**
     * 
     * @return
     *     returns java.util.List<ws.haruhi.sos.test.User>
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "")
    @RequestWrapper(localName = "list", targetNamespace = "http://sos.haruhi.ws/test/", className = "ws.haruhi.sos.test.List")
    @ResponseWrapper(localName = "listResponse", targetNamespace = "http://sos.haruhi.ws/test/", className = "ws.haruhi.sos.test.ListResponse")
    public List<User> list();

    /**
     * 
     * @param password
     * @param username
     * @return
     *     returns ws.haruhi.sos.test.User
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://sos.haruhi.ws/test/", className = "ws.haruhi.sos.test.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://sos.haruhi.ws/test/", className = "ws.haruhi.sos.test.LoginResponse")
    public User login(
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password);

}
