
package sos.haruhi.ws.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IUserService", targetNamespace = "http://sos.haruhi.ws/test/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IUserService {


    /**
     * 
     * @param user
     * @throws UserException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "add", targetNamespace = "http://sos.haruhi.ws/test/", className = "sos.haruhi.ws.client.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://sos.haruhi.ws/test/", className = "sos.haruhi.ws.client.AddResponse")
    public void add(
        @WebParam(name = "user", targetNamespace = "")
        User user)
        throws UserException_Exception
    ;

    /**
     * 
     * @param username
     */
    @WebMethod
    @RequestWrapper(localName = "del", targetNamespace = "http://sos.haruhi.ws/test/", className = "sos.haruhi.ws.client.Del")
    @ResponseWrapper(localName = "delResponse", targetNamespace = "http://sos.haruhi.ws/test/", className = "sos.haruhi.ws.client.DelResponse")
    public void del(
        @WebParam(name = "username", targetNamespace = "")
        String username);

    /**
     * 
     * @return
     *     returns java.util.List<sos.haruhi.ws.client.User>
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "")
    @RequestWrapper(localName = "list", targetNamespace = "http://sos.haruhi.ws/test/", className = "sos.haruhi.ws.client.List")
    @ResponseWrapper(localName = "listResponse", targetNamespace = "http://sos.haruhi.ws/test/", className = "sos.haruhi.ws.client.ListResponse")
    public List<User> list();

    /**
     * 
     * @param password
     * @param username
     * @return
     *     returns sos.haruhi.ws.client.User
     * @throws UserException_Exception
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://sos.haruhi.ws/test/", className = "sos.haruhi.ws.client.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://sos.haruhi.ws/test/", className = "sos.haruhi.ws.client.LoginResponse")
    public User login(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password)
        throws UserException_Exception
    ;

    /**
     * 
     * @param file
     */
    @WebMethod
    @RequestWrapper(localName = "upload", targetNamespace = "http://sos.haruhi.ws/test/", className = "sos.haruhi.ws.client.Upload")
    @ResponseWrapper(localName = "uploadResponse", targetNamespace = "http://sos.haruhi.ws/test/", className = "sos.haruhi.ws.client.UploadResponse")
    public void upload(
        @WebParam(name = "file", targetNamespace = "")
        byte[] file);

}
