package org.example.my;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
/**
 * 接口
 */

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 *
 */
@WebService(name = "IMyservice", targetNamespace = "http://www.example.org/my/")
public interface IMyservice {


    /**
     *
     * @param b
     * @param a
     * @param license 头信息
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "addResult", targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://www.example.org/my/", className = "org.example.my.AddType")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://www.example.org/my/", className = "org.example.my.AddResponseType")
    public int add(
            @WebParam(name = "a", targetNamespace = "")
                    int a,
            @WebParam(name = "b", targetNamespace = "")
                    int b,
            @WebParam(name = "license", header=true)
                    String license);

}