
package com.haruhi.com.haruhi.other;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IMathService", targetNamespace = "http://another.haruhi.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IMathService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sum", targetNamespace = "http://another.haruhi.com/", className = "com.haruhi.com.haruhi.other.Sum")
    @ResponseWrapper(localName = "sumResponse", targetNamespace = "http://another.haruhi.com/", className = "com.haruhi.com.haruhi.other.SumResponse")
    @Action(input = "http://another.haruhi.com/IMathService/sumRequest", output = "http://another.haruhi.com/IMathService/sumResponse")
    public int sum(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
