
package com.haruhi.com.haruhi.other;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MathServiceImplService", targetNamespace = "http://another.haruhi.com/", wsdlLocation = "http://localhost:9999/ws?wsdl")
public class MathServiceImplService
    extends Service
{

    private final static URL MATHSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MATHSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName MATHSERVICEIMPLSERVICE_QNAME = new QName("http://another.haruhi.com/", "MathServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/ws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MATHSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        MATHSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public MathServiceImplService() {
        super(__getWsdlLocation(), MATHSERVICEIMPLSERVICE_QNAME);
    }

    public MathServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MATHSERVICEIMPLSERVICE_QNAME, features);
    }

    public MathServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, MATHSERVICEIMPLSERVICE_QNAME);
    }

    public MathServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MATHSERVICEIMPLSERVICE_QNAME, features);
    }

    public MathServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MathServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IMathService
     */
    @WebEndpoint(name = "MathServiceImplPort")
    public IMathService getMathServiceImplPort() {
        return super.getPort(new QName("http://another.haruhi.com/", "MathServiceImplPort"), IMathService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IMathService
     */
    @WebEndpoint(name = "MathServiceImplPort")
    public IMathService getMathServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://another.haruhi.com/", "MathServiceImplPort"), IMathService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MATHSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw MATHSERVICEIMPLSERVICE_EXCEPTION;
        }
        return MATHSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
