
package com.haruhi.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IService", targetNamespace = "http://ws.haruhi.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IService {


    /**
     * 
     * @param a
     * @param b
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "addResult", targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://ws.haruhi.com/", className = "com.haruhi.ws.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://ws.haruhi.com/", className = "com.haruhi.ws.AddResponse")
    @Action(input = "http://ws.haruhi.com/IService/addRequest", output = "http://ws.haruhi.com/IService/addResponse")
    public int add(
        @WebParam(name = "a", targetNamespace = "")
        int a,
        @WebParam(name = "b", targetNamespace = "")
        int b);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "min", targetNamespace = "http://ws.haruhi.com/", className = "com.haruhi.ws.Min")
    @ResponseWrapper(localName = "minResponse", targetNamespace = "http://ws.haruhi.com/", className = "com.haruhi.ws.MinResponse")
    @Action(input = "http://ws.haruhi.com/IService/minRequest", output = "http://ws.haruhi.com/IService/minResponse")
    public int min(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
